#  Copyright 2021 CNM Ingenuity, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
name: Extract
description: "Prepare to run & autograde JAR-packaged tests."
inputs:
  workspace:
    description: "Base directory of project under test."
    required: true
  test-archive:
    description: "Base name for JAR file ('.jar' appended)."
    required: true
  build-system: 
    description: "Build system used for the project (Maven or Gradle)."
    required: false
    default: gradle
  extract-destination:
    description: "Destination subdirectory of extracted test classes & configuration."
    required: false
    default: autograding
  configuration-destination:
    description: "Destination subdirectory for autograding configuration."
    required: false
    default: .github/classroom
  gradle-project:
    description: "rootProject.name for dynamic creation of Gradle project."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Extract tests
      run: ${{ github.action_path }}/extract.sh ${{ github.action_path }}/archives/${{ inputs.test-archive }}.jar ${{ inputs.workspace }}/${{ inputs.extract-destination }}/
      shell: bash
    - name: Copy Gradle configuration
      run: ${{ github.action_path }}/copy.sh ${{ inputs.workspace }}/${{ inputs.extract-destination }}/autograding.json ${{ inputs.workspace }}/${{ inputs.configuration-destination }}/
      shell: bash
    - name: Copy Gradle script
      run: cp -r ${{ github.action_path }}/gradle/. ${{ inputs.workspace }}/
      shell: bash
    - name: Make gradlew executable
      run: chmod +x ${{ inputs.workspace }}/gradlew
      shell: bash
